# data-raw/complications.R
# Run this script to regenerate data/complication_definitions.rda
# and data/maude_complication_index.rda
#
# source("data-raw/complications.R")

# Ablation ----
complication_definitions <- list(
  # Pericardial Effusion / Cardiac Tamponade / Pericarditis ----
  pericardial = list(
    title = "Pericardial Effusion / Cardiac Tamponade / Pericarditis",
    definition = "Pericardial complication during or after AF catheter ablation: effusion (blood or serous), frank tamponade, or post-ablation pericarditis (with or without effusion). Mechanisms: atrial wall or transseptal-needle perforation, thermal injury with delayed rupture, over-anticoagulation, inflammatory pericarditis. Cues: hypotension, pulsus paradoxus, pleuritic chest pain, friction rub, effusion on echo, pericardiocentesis, surgical drainage, NSAIDs/colchicine. Includes acute intraprocedural and delayed (hours to days) presentations.",
    classification = list(
      pericarditis_without_effusion = "Pericarditis (pleuritic chest pain, possible friction rub) without significant effusion. Managed with NSAIDs, colchicine, or observation.",
      trivial_effusion = "Small or trace effusion at end of case or on post-procedure imaging. No hemodynamic compromise, no drainage. Observation with or without anti-inflammatories.",
      moderate_no_intervention = "Moderate effusion with symptoms (chest pain, dyspnea, tachycardia) but no drainage. May include holding or reversing anticoagulation and medical therapy.",
      tamponade_pericardiocentesis = "Hemodynamically significant effusion or tamponade requiring percutaneous pericardiocentesis. Hypotension, pulsus paradoxus, or chamber collapse prompting emergent drainage.",
      tamponade_surgical = "Tamponade or perforation requiring surgery: pericardial window, thoracotomy, sternotomy, or atrial wall repair.",
      insufficient_info = "Pericardial effusion, tamponade, or pericarditis mentioned but detail insufficient to determine intervention or management."
    )
  ),

  # Cerebrovascular Event ----
  stroke = list(
    title = "Cerebrovascular Event",

    definition = "Ischemic stroke, hemorrhagic stroke, transient ischemic attack (TIA), or systemic thromboembolism during or after AF ablation. Mechanisms: thrombus on catheters or sheaths, air embolism (transseptal puncture, catheter exchange), char embolism, dislodged pre-existing left atrial thrombus. Cues: focal deficit (weakness, aphasia, visual change), altered mental status, infarct or hemorrhage on CT/MRI, systemic embolism. Includes clinically apparent events and silent (asymptomatic) cerebral lesions on post-procedure DWI-MRI.",

    classification = list(
      tia = "Transient focal deficit fully resolving within 24 hours with no infarct on imaging. Return to neurologic baseline.",
      minor_stroke = "Non-disabling stroke: mild residual deficit at discharge or follow-up (modified Rankin scale <2, or NIHSS <=3), or labeled 'minor stroke.' Also silent cerebral lesions on post-procedure MRI, if reported.",
      major_stroke = "Disabling stroke: persistent deficit with lasting functional disability (modified Rankin scale >=2 attributable to the event), ICU-level care, or neurosurgical intervention. Includes large-territory infarction and symptomatic intracranial hemorrhage.",
      fatal_stroke = "Cerebrovascular event that directly caused or substantially contributed to death.",
      systemic_embolism = "Thromboembolism to a non-cerebral territory (mesenteric, renal, or peripheral arterial) in the peri-procedural period.",
      insufficient_info = "Cerebrovascular or embolic event described but deficit severity, symptom duration, or outcome unclear."
    )
  ),

  # Vascular Access Complication ----
  vascular = list(
    title = "Vascular Access Complication",

    definition = "Complication of percutaneous vascular access, usually at the femoral venous or arterial puncture site. Cues: groin hematoma, swelling, access-site pain, pseudoaneurysm, arteriovenous (AV) fistula, retroperitoneal hemorrhage, or bleeding requiring transfusion. Also access-related deep vein thrombosis or pulmonary embolism and catheter/sheath vascular injury. EXCLUDES bleeding at non-access sites.",

    classification = list(
      minor_hematoma = "Groin hematoma or minor access-site bleeding managed with compression, observation, or bed rest only. No transfusion or procedural repair.",
      major_hematoma_transfusion = "Access-site hematoma or bleeding requiring transfusion but not surgical or interventional repair. Includes hemoglobin drop of 2 g/dL or more.",
      pseudoaneurysm = "Femoral pseudoaneurysm requiring intervention: ultrasound-guided thrombin injection, compression, or surgical repair.",
      av_fistula = "Access-site arteriovenous fistula. Managed by observation, compression, or surgical repair per size and symptoms.",
      retroperitoneal = "Retroperitoneal hemorrhage from femoral vessel injury. Flank or abdominal pain, hemodynamic instability, hemoglobin drop. May require transfusion, embolization, or surgery.",
      vte = "Access- or catheter-related deep vein thrombosis or pulmonary embolism.",
      insufficient_info = "Vascular access complication described but type or severity unclear."
    )
  ),

  # Pulmonary Vein Stenosis ----
  pv_stenosis = list(
    title = "Pulmonary Vein Stenosis",

    definition = "Narrowing of one or more pulmonary veins from ablation within or at the PV ostium. Incidence fell substantially with the shift from ostial to antral isolation. Seen with radiofrequency and cryoballoon; rare with pulsed field ablation (tissue selectivity). Cues: dyspnea, hemoptysis, recurrent pulmonary infection, PV narrowing on CT/MRI. Onset often weeks to months after ablation.",

    classification = list(
      asymptomatic = "PV narrowing on follow-up imaging (CT, MRI, or TEE), patient asymptomatic. Includes mild (<50% luminal reduction) and moderate (50-70%) stenosis without symptoms.",
      symptomatic_medical = "Symptomatic PV stenosis (dyspnea, hemoptysis, recurrent pneumonia, reduced exercise tolerance) managed medically or by observation without intervention.",
      intervention_required = "PV stenosis requiring balloon angioplasty or stent. Usually severe (>70% luminal reduction) with limiting symptoms.",
      complete_occlusion = "Complete occlusion of one or more pulmonary veins on imaging. May be asymptomatic with adequate collaterals; most severe anatomic finding.",
      insufficient_info = "PV stenosis or related symptoms mentioned but imaging, severity, or management insufficient to grade."
    )
  ),

  # Esophageal Injury ----
  esophageal = list(
    title = "Esophageal Injury",

    definition = "Esophageal injury from energy delivery on the posterior left atrial wall (adjacent to the anterior esophagus). Spectrum: superficial mucosal injury to the catastrophic, often fatal atrioesophageal fistula (AEF). All energy modalities; lower thermal risk with PFA (tissue selectivity). Cues: chest or back pain, dysphagia, odynophagia, fever, endoscopic erythema or ulceration, mediastinal air on CT, neurologic symptoms from air embolism via fistula. Also periesophageal vagal injury causing gastroparesis: nausea, vomiting, early satiety, bloating.",

    classification = list(
      mucosal = "Superficial injury limited to mucosal erythema, erosion, or shallow ulcer on endoscopy. Managed with proton pump inhibitors and diet. No perforation or fistula.",
      deep_ulceration = "Deep ulceration beyond the mucosa without fistula. Extended medical management (sucralfate, IV PPI) and surveillance imaging.",
      atrioesophageal_fistula = "AEF confirmed on imaging (mediastinal or left atrial air on CT) or at surgery. Life-threatening; typically 2-5 weeks post-ablation with fever, neurologic symptoms from air or septic embolism, hematemesis, or sepsis.",
      gastroparesis = "Symptomatic gastroparesis (nausea, vomiting, early satiety, bloating, delayed gastric emptying) from periesophageal vagal injury during posterior wall ablation. Self-limited to debilitating.",
      insufficient_info = "Esophageal symptoms, findings, or concern described but injury depth or outcome unclear."
    )
  ),

  # Phrenic Nerve Injury ----
  phrenic = list(
    title = "Phrenic Nerve Injury",

    definition = "Right or left phrenic nerve injury during ablation causing diaphragmatic paresis or paralysis. Right nerve most affected (proximity to right superior PV and superior vena cava). Most common with cryoballoon of the right superior PV; also radiofrequency, rarely PFA. Cues: loss of diaphragmatic excursion during the procedure (fluoroscopic or pacing-monitored), post-procedure dyspnea, elevated hemidiaphragm on chest X-ray, reduced inspiratory effort.",

    classification = list(
      intraprocedural_only = "Phrenic capture lost or reduced diaphragmatic excursion noted intraprocedurally, prompting ablation cessation. Function recovered before end of case or by discharge.",
      transient = "Palsy persisting beyond the procedure but recovering fully within 12 months. Includes elevated hemidiaphragm at discharge with later recovery.",
      persistent = "Palsy still present at 12 months or later, or described as permanent. May have chronic exertional dyspnea and persistent hemidiaphragm elevation.",
      insufficient_info = "Phrenic injury or elevated hemidiaphragm described but follow-up insufficient to determine recovery."
    )
  ),

  # Procedure-Related Arrhythmia ----
  arrhythmia = list(
    title = "Procedure-Related Arrhythmia",

    definition = "New arrhythmia caused by the ablation itself, distinct from recurrence of the original AF. Includes iatrogenic left atrial macro-reentrant tachycardia or atypical flutter from lesion-set gaps, new AV block from septal ablation or conduction-system trauma, inappropriate sinus tachycardia from autonomic modulation, and new ventricular or organized atrial proarrhythmia. EXCLUDES recurrent pre-existing AF and expected blanking-period reconnection arrhythmias.",

    classification = list(
      self_terminating = "Iatrogenic arrhythmia terminating spontaneously or with brief pacing maneuvers, no recurrence, no added intervention.",
      cardioversion_or_medical = "Requires electrical cardioversion, antiarrhythmic, or rate-control drugs. Includes persistent atrial tachycardia or flutter managed medically without repeat ablation.",
      repeat_ablation = "Requires a repeat ablation (e.g., mapping and ablation of a gap-related macro-reentrant tachycardia or flutter circuit).",
      device_implant = "Requires a permanent pacemaker or ICD. Includes complete AV block from septal ablation or catheter trauma needing permanent pacing.",
      insufficient_info = "New ablation-related arrhythmia described but type, management, or outcome unclear."
    )
  ),

  # Coronary Artery Injury / Spasm ----
  coronary = list(
    title = "Coronary Artery Injury / Spasm",

    definition = "Coronary artery spasm, occlusion, or injury from ablation energy near the coronaries. Most reported with pulsed field ablation (PFA), whose high-voltage field can stimulate vascular smooth muscle: focal left circumflex spasm during mitral isthmus ablation and right coronary spasm during cavotricuspid isthmus ablation are the recognized patterns. Delayed diffuse spasm (possibly hemolysis-related nitric oxide depletion) also described with PFA. Cues: ST-segment changes, chest pain, hemodynamic instability, angiography findings, intraprocedural nitroglycerin. Rare with radiofrequency, mainly epicardial ablation.",

    classification = list(
      transient_spasm = "Spasm resolving promptly with cessation of energy and/or intracoronary or IV nitroglycerin. No myocardial injury (normal troponin). No lasting ischemia.",
      sustained_spasm = "Spasm requiring prolonged vasodilators, occurring remote/delayed from energy delivery, or recurring after resolution. May include troponin rise not meeting MI criteria.",
      myocardial_infarction = "Acute MI from occlusion or sustained spasm. Includes STEMI, NSTEMI with significant troponin rise plus ischemic symptoms or ECG changes, and occlusion requiring emergent PCI.",
      coronary_stenosis = "Coronary narrowing or remodeling on follow-up angiography or OCT attributed to ablation injury. Recently described with PFA near coronary vessels.",
      insufficient_info = "Coronary symptoms, ST changes, or concern described but mechanism, severity, or outcome unclear."
    )
  ),

  # Hemolysis / Acute Kidney Injury ----
  hemolysis = list(
    title = "Hemolysis / Acute Kidney Injury",

    definition = "Intravascular hemolysis from electroporation of red blood cells, predominantly with pulsed field ablation (PFA). High-voltage pulsed fields rupture erythrocytes (transmembrane pore formation, osmotic swelling). Cues: elevated plasma free hemoglobin, elevated LDH, hemoglobinuria (dark urine), and in severe cases acute kidney injury (AKI) from heme-mediated proximal tubular damage. Free hemoglobin also scavenges nitric oxide (may contribute to urinary retention, coronary spasm, hypertension). Risk rises with number of PFA applications and catheter-tissue contact. Severe AKI requiring dialysis is rare (~0.03%, MANIFEST-17K).",

    classification = list(
      laboratory_only = "Lab evidence of hemolysis (elevated free hemoglobin, LDH, hemoglobinuria) without significant renal dysfunction or other end-organ effect. Self-resolving within 24-48 hours.",
      aki_no_dialysis = "Hemolysis-induced AKI (significant serum creatinine rise) managed conservatively with IV hydration, no renal replacement.",
      aki_dialysis = "Severe hemolysis-induced AKI requiring temporary or sustained renal replacement therapy (hemodialysis).",
      insufficient_info = "Hemolysis, dark urine, elevated LDH, or renal dysfunction mentioned but severity unclear."
    )
  ),

  # Respiratory / Pulmonary Complication ----
  respiratory = list(
    title = "Respiratory / Pulmonary Complication",

    definition = "Pulmonary or thoracic complication NOT from pulmonary vein stenosis (see pv_stenosis) or phrenic nerve injury (see phrenic). Includes pneumothorax (subclavian, internal jugular, or epicardial access), hemothorax, pulmonary hemorrhage or hemoptysis (reported with PFA), bronchial injury, pulmonary edema, and pulmonary infection. Cues: dyspnea, chest pain, reduced breath sounds, chest tube placement, chest imaging findings.",

    classification = list(
      mild = "Minor, managed conservatively: small pneumothorax resolving without chest tube, transient hemoptysis, or mild pulmonary edema treated with diuretics.",
      moderate_intervention = "Requires procedure: chest tube for pneumothorax or hemothorax, or significant pulmonary hemorrhage requiring bronchoscopy.",
      severe = "Requires ICU care, mechanical ventilation, surgery, or prolonged hospitalization.",
      insufficient_info = "Respiratory or pulmonary complication described but severity unclear."
    )
  ),

  # Procedure-Related Infection ----
  infection = list(
    title = "Procedure-Related Infection",

    definition = "Infection attributable to the ablation. Includes access-site infection (cellulitis, abscess), endocarditis from catheter-introduced organisms, bacteremia or sepsis from intravascular instrumentation, mediastinitis (may accompany esophageal injury), and post-procedure pneumonia. Cues: fever, elevated white blood cell count, positive blood cultures, wound erythema or drainage, antibiotics for a suspected procedure-related source. EXCLUDES infections unrelated to the procedure.",

    classification = list(
      local = "Localized access-site infection (cellulitis, superficial wound) managed with oral antibiotics, no hospitalization.",
      systemic_iv_antibiotics = "Systemic infection (bacteremia, pneumonia, UTI) requiring IV antibiotics or hospitalization, without hemodynamic instability or end-organ damage.",
      sepsis = "Sepsis or septic shock from a procedure-related source (endocarditis, mediastinitis, septic embolism). Requires ICU-level care, vasopressors, or surgical source control.",
      insufficient_info = "Infection or related findings described but source, extent, or severity unclear."
    )
  ),

  # Procedure-Related Death ----
  death = list(
    title = "Procedure-Related Death",

    definition = "Death during or after AF ablation judged related to the procedure or one of its complications. Multifactorial: cardiac tamponade, atrioesophageal fistula, massive stroke, anesthesia event, coronary occlusion, or other procedural causes. Overall incidence ~0.05-0.1%. Narrative may state death outright or describe a course leading to it (refractory cardiac arrest, withdrawal of care). Captures death as the final outcome; the underlying mechanism may also warrant another category (pericardial, stroke, esophageal).",

    classification = list(
      intraprocedural = "Death during the procedure itself, in the electrophysiology laboratory or operating room.",
      periprocedural = "Death within 30 days, outside the procedural setting, attributed to a procedural complication.",
      delayed = "Death more than 30 days post-ablation attributed to a procedural complication (late atrioesophageal fistula, late PV stenosis with pulmonary consequences).",
      insufficient_info = "Death indicated but timing or cause relative to the procedure unclear."
    )
  ),

  # Device / Equipment Malfunction ----
  device_malfunction = list(
    title = "Device / Equipment Malfunction",

    definition = "Failure or malfunction of the ablation catheter, energy generator, mapping system, or ancillary equipment (sheaths, transseptal needles, irrigation pump, recording system), regardless of whether it caused patient injury. In MAUDE often filed under the 'Malfunction' event type with Annex A device-problem codes. Cues: catheter fracture, tip detachment, generator error codes, impedance faults, software or firmware failure, irrigation failure, mapping-system crash, inability to deliver energy. If it also caused a clinical complication, co-assign the relevant clinical category.",

    classification = list(
      no_procedure_impact = "Malfunction identified and resolved without impact; procedure completed with the same or replacement equipment.",
      procedure_altered = "Malfunction required a change in strategy, backup equipment, or premature termination, but no direct patient injury.",
      patient_injury = "Malfunction directly caused or contributed to a patient injury. Also classify the injury under the appropriate clinical category.",
      insufficient_info = "Device malfunction described but procedure or patient impact unclear."
    )
  ),

  # No Patient Harm ----
  no_harm = list(
    title = "No Patient Harm",

    definition = "Report describes a device problem, procedural deviation, near-miss, or other reportable occurrence but explicitly states no patient injury or harm occurred. Accounts for reports filed to satisfy regulatory obligations that do not represent a clinical complication. Cues: 'no patient harm,' 'no adverse outcome,' 'no clinical consequence,' 'no impact to the patient.' Assign only when absence of harm is affirmatively stated, not merely when harm is unmentioned.",

    classification = list(
      confirmed_no_harm = "Narrative explicitly and clearly states no patient harm occurred.",
      probable_no_harm = "Circumstances strongly suggest no harm, but no explicit confirming statement.",
      insufficient_info = "Insufficient information to determine whether patient harm occurred."
    )
  ),

  # Other Complication ----
  other = list(
    title = "Other Complication",

    definition = "Procedure-related adverse event not fitting any preceding category; a residual for real but uncommon complications. Examples: cardiac valve injury (mitral or tricuspid damage from catheter manipulation, chordal entanglement, new or worsened regurgitation), vasovagal or autonomic response (profound bradycardia, asystole, or hypotension during energy delivery, especially PFA near ganglionated plexi), iatrogenic atrial septal defect from transseptal puncture needing closure, stiff left atrium syndrome, radiation skin injury, contrast allergy or anaphylaxis, anesthesia complications (aspiration, airway injury, drug reaction), cardiogenic shock not from tamponade, acute heart failure, urinary retention, skin burns, musculoskeletal injury from positioning or PFA skeletal-muscle stimulation. Use only when no more specific category fits.",

    classification = list(
      minor = "Self-limited or minimal intervention; no prolonged hospitalization; resolved without lasting sequelae.",
      moderate = "Requires additional treatment, prolonged hospitalization, or a secondary procedure, without lasting disability or life-threatening consequence.",
      severe = "Life-threatening, lasting disability, major intervention, or significantly altered clinical course.",
      insufficient_info = "Complication in this category described but severity insufficient to grade."
    )
  )
)

# MAUDE complication index ----

# Keep this explicit and hand-editable. Each category contains normalized
# MAUDE problem terms that can be used to narrow the LLM's starting set.
# Terms may overlap across categories.
# These are normalized terms which means won't be exact matches

maude_complication_index <- list(
  pericardial = c(
    "blood transfusion",
    "cardiac perforation",
    "cardiac tamponade",
    "cardiogenic shock",
    "cardiovascular dysfunction insufficiency",
    "chest pain",
    "dyspnea",
    "great vessel perforation",
    "hemodynamic instability",
    "intraoperative cardiac injury",
    "low blood pressure hypotension",
    "pericardial effusion",
    "pericarditis",
    "presyncope",
    "shock",
    "syncope fainting"
  ),
  stroke = c(
    "air embolism",
    "altered state of consciousness",
    "balance problems",
    "brain injury",
    "cerebral edema",
    "cerebral hyperperfusion syndrome",
    "cerebral ventriculomegaly",
    "cognitive changes",
    "coma",
    "confusion disorientation",
    "convulsion clonic",
    "convulsion seizure",
    "convulsion tonic",
    "decreased level of consciousness",
    "delirium",
    "dizziness",
    "diplopia double vision",
    "dysphasia",
    "embolism embolus",
    "encephalopathy",
    "facial paralysis",
    "fat embolism",
    "foreign body embolism",
    "headache",
    "hemorrhagic stroke",
    "hydrocephalus",
    "hypoesthesia",
    "idiopathic intracranial hypertension",
    "intracranial hemorrhage",
    "intracranial pressure increased",
    "ischemia stroke",
    "loss of consciousness",
    "memory loss impairment",
    "nervous system",
    "nervous system injury",
    "numbness",
    "paralysis",
    "paraplegia",
    "paresthesia",
    "paresis",
    "quadriplegia",
    "speech disorder",
    "status epilepticus",
    "stroke cva",
    "thromboembolism",
    "thrombosis thrombus",
    "transient ischemic attack",
    "unspecified nervous system problem",
    "vertigo"
  ),
  vascular = c(
    "air embolism",
    "anemia",
    "aneurysm",
    "aneurysm expansion",
    "aortic dissection",
    "blood transfusion",
    "bruise contusion",
    "cephalohematoma",
    "coagulation disorder",
    "diminished pulse pressure",
    "disseminated intravascular coagulation dic",
    "ecchymosis",
    "easy bruising",
    "epistaxis",
    "exsanguination",
    "extravasation",
    "fistula",
    "gastrointestinal hemorrhage",
    "great vessel perforation",
    "hematemesis",
    "hematoma",
    "hematuria",
    "hemorrhage blood loss bleeding",
    "hypovolemic shock",
    "intra abdominal hemorrhage",
    "low blood pressure hypotension",
    "perforation of vessels",
    "pseudoaneurysm",
    "pulmonary embolism",
    "reduced blood flow",
    "retroperitoneal hemorrhage",
    "ruptured aneurysm",
    "thromboembolism",
    "thrombocytopenia",
    "thrombosis thrombus",
    "unintended loss of vascular access",
    "unspecified vascular problem",
    "vascular dissection",
    "vascular system",
    "vasculitis"
  ),
  pv_stenosis = c(
    "dyspnea",
    "hemoptysis",
    "pleural effusion",
    "pneumonia",
    "pulmonary dysfunction",
    "pulmonary hypertension",
    "pulmonary infarction"
  ),
  esophageal = c(
    "abdominal distention",
    "achalasia",
    "chest pain",
    "dysphagia odynophagia",
    "endoscopic diagnostic procedure",
    "fistula",
    "gastrointestinal regurgitation",
    "gastroesophageal burn",
    "heartburn indigestion",
    "laceration s of esophagus",
    "mediastinal shift",
    "nausea",
    "perforation of esophagus",
    "sepsis",
    "stenosis of the esophagus",
    "vomiting"
  ),
  phrenic = c(
    "breathing related sleep disorder",
    "decreased peak expiratory flow rate",
    "dyspnea",
    "forced expiratory volume decreased",
    "hiccups",
    "hypoventilation",
    "hypoxia",
    "hypoxia in utero",
    "increased peak expiratory flow rate",
    "respiratory failure",
    "respiratory insufficiency",
    "unspecified respiratory problem",
    "ventilator dependent"
  ),
  arrhythmia = c(
    "arrhythmia",
    "asystole",
    "atrial fibrillation",
    "atrial flutter",
    "bradycardia",
    "ectopic heartbeat",
    "heart block",
    "idioventricular rhythm",
    "non specific ekg ecg changes",
    "presyncope",
    "syncope fainting",
    "tachycardia",
    "ventricular fibrillation"
  ),
  coronary = c(
    "angina",
    "cardiogenic shock",
    "chest pain",
    "coronary obstruction occlusion",
    "hemodynamic instability",
    "high blood pressure hypertension",
    "ischemia",
    "ischemia stroke",
    "ischemic heart disease",
    "low blood pressure hypotension",
    "myocardial infarction",
    "reduced blood flow",
    "reperfusion injury",
    "syncope fainting",
    "vasoconstriction"
  ),
  hemolysis = c(
    "anemia",
    "blood transfusion",
    "hematuria",
    "hemolysis",
    "hemolytic anemia",
    "kidney injury",
    "renal impairment",
    "renal failure",
    "uremia",
    "unspecified kidney or urinary problem",
    "urinary retention"
  ),
  respiratory = c(
    "abnormal blood gases",
    "adult respiratory distress syndrome",
    "airway obstruction",
    "apnea",
    "aspiration inhalation",
    "aspiration pneumonitis",
    "asthma",
    "breathing related sleep disorder",
    "bronchial hemorrhage",
    "bronchitis",
    "bronchopneumonia",
    "bronchospasm",
    "choking",
    "chronic obstructive pulmonary disease copd",
    "cough",
    "cyanosis",
    "decreased respiratory rate",
    "dyspnea",
    "forced expiratory volume decreased",
    "hemoptysis",
    "hemothorax",
    "high pulmonary arterial wedge pressure",
    "hyperventilation",
    "hypoventilation",
    "hypoxia",
    "hypoxia in utero",
    "increased respiratory rate",
    "low pulmonary arterial wedge pressure",
    "overinflation of lung",
    "pleural effusion",
    "pleural empyema",
    "pneumonia",
    "pneumothorax",
    "pulmonary dysfunction",
    "pulmonary edema",
    "pulmonary embolism",
    "pulmonary emphysema",
    "pulmonary hypertension",
    "pulmonary infarction",
    "pulmonary valve insufficiency regurgitation",
    "pulmonary valve stenosis",
    "respiratory acidosis",
    "respiratory alkalosis",
    "respiratory arrest",
    "respiratory distress syndrome of newborns",
    "respiratory failure",
    "respiratory insufficiency",
    "respiratory system",
    "respiratory tract infection",
    "stacking breaths",
    "strangulation",
    "unintended extubation",
    "unspecified respiratory problem",
    "upper respiratory tract injury",
    "upper respiratory tract irritation",
    "ventilator dependent",
    "wheezing"
  ),
  infection = c(
    "abscess",
    "aseptic loosening",
    "bacteremia",
    "bacterial infection",
    "bronchopneumonia",
    "cellulitis",
    "chills",
    "cytomegalovirus cmv infection",
    "drug resistant bacterial infection",
    "ear infection",
    "endocarditis",
    "encephalitis",
    "exposure to contaminated device risk of infection",
    "eye infections",
    "fever",
    "fluid discharge",
    "fungal infection",
    "hepatitis",
    "high white blood cell count",
    "infections",
    "infectious otitis externa",
    "infectious otitis media",
    "infective keratitis",
    "intraocular infection",
    "kidney infection",
    "mastoiditis",
    "medical device site infection",
    "meningitis",
    "osteomyelitis",
    "pelvic inflammatory disease",
    "peritonitis",
    "pharyngitis",
    "pneumonia",
    "post operative wound infection",
    "purulent discharge",
    "pyogenic infection",
    "respiratory tract infection",
    "rhinitis",
    "sepsis",
    "septic loosening",
    "septic shock",
    "sexually transmitted infection",
    "skin infection",
    "subclinical infection",
    "swollen lymph nodes glands",
    "toxemia",
    "toxic shock syndrome",
    "unspecified infection",
    "urinary tract infection",
    "viral infection",
    "wound dehiscence",
    "wound infection",
    "wound odor"
  ),
  death = c(
    "brain death",
    "death",
    "intrauterine fetal death"
  ),
  device_malfunction = c(
    "aborted charge",
    "absence of treatment",
    "accessory incompatible",
    "activation failure",
    "activation problem",
    "additional device required",
    "adhesive too strong",
    "air gas in device",
    "alarm not visible",
    "ambient noise problem",
    "ambient temperature problem",
    "application network problem",
    "application program freezes becomes nonfunctional",
    "application program problem",
    "application program problem dose calculation error",
    "application program problem medication error",
    "application program problem parameter calculation error",
    "application program problem power calculation error",
    "application program version or upgrade problem",
    "application security problem",
    "arcing",
    "arcing at paddles",
    "arcing of electrodes",
    "audible prompt feedback problem",
    "backflow",
    "battery problem",
    "battery problem high impedance",
    "battery problem low impedance",
    "biocompatibility",
    "biofilm coating in device",
    "blocked connection",
    "break",
    "burst container or vessel",
    "calcified",
    "capacitative coupling",
    "capturing problem",
    "change in therapeutic response",
    "charging problem",
    "circuit failure",
    "clumping in device or device ingredient",
    "coagulation in device or device ingredient",
    "collapse",
    "complete blockage",
    "complete loss of power",
    "component incompatible",
    "component misassembled",
    "component missing",
    "component or accessory incompatibility",
    "computer operating system problem",
    "computer system security problem",
    "contamination",
    "contamination of device ingredient or reagent",
    "continuous firing",
    "corroded",
    "crack",
    "cross reactivity",
    "damaged thread",
    "data back up problem",
    "data problem",
    "date time related software problem",
    "decoupling",
    "decrease in pressure",
    "decrease in suction",
    "decreased pump speed",
    "decreased sensitivity",
    "defective alarm",
    "defective component",
    "defective device",
    "defibrillation stimulation problem",
    "deflation problem",
    "deformation due to compressive stress",
    "degraded",
    "delayed alarm",
    "delayed charge time",
    "delayed program or algorithm execution",
    "delivered as unsterile product",
    "dent in material",
    "detachment of device or device component",
    "device alarm system",
    "device appears to trigger rejection",
    "device contaminated at the user facility",
    "device contaminated during manufacture or shipping",
    "device contamination with body fluid",
    "device contamination with chemical or other material",
    "device damaged by another device",
    "device damaged prior to use",
    "device device incompatibility",
    "device difficult to maintain",
    "device difficult to program or calibrate",
    "device difficult to setup or prepare",
    "device dislodged or dislocated",
    "device displays incorrect message",
    "device emits odor",
    "device explantation",
    "device fell",
    "device handling problem",
    "device in backup mode",
    "device ingredient or reagent problem",
    "device label look alike",
    "device markings labelling problem",
    "device misassembled during manufacturing shipping",
    "device packaging look alike",
    "device provides uninformative message",
    "device provides unintelligible message",
    "device remains activated",
    "device repositioning",
    "device reprocessing problem",
    "device revision or replacement",
    "device sensing problem",
    "device slipped",
    "device stenosis",
    "device tipped over",
    "device unsafe to use in environment",
    "difficult or delayed activation",
    "difficult or delayed positioning",
    "difficult or delayed separation",
    "difficult to advance",
    "difficult to flush",
    "difficult to fold unfold or collapse",
    "difficult to insert",
    "difficult to interrogate",
    "difficult to open or close",
    "difficult to open or remove packaging material",
    "difficult to remove",
    "disconnection",
    "display difficult to read",
    "display or visual feedback problem",
    "disruption of subsequent medical procedure",
    "dull blunt",
    "ejection problem",
    "electrical overstress",
    "electrical power problem",
    "electrical shorting",
    "electro static discharge",
    "electromagnetic compatibility problem",
    "electromagnetic interference",
    "emergency power failure",
    "endoleaks",
    "energy output problem",
    "energy spectrum incorrect",
    "entrapment of device",
    "environmental particulates",
    "erratic or intermittent display",
    "erratic results",
    "excess flow or over infusion",
    "excessive cooling",
    "excessive heating",
    "expiration date error",
    "explosion",
    "expulsion",
    "extra components",
    "fail safe did not operate",
    "fail safe problem",
    "failure of device to self test",
    "failure to advance",
    "failure to align",
    "failure to analyze signal",
    "failure to auto stop",
    "failure to back up",
    "failure to calibrate",
    "failure to capture",
    "failure to charge",
    "failure to clean adequately",
    "failure to conduct",
    "failure to convert rhythm",
    "failure to convert to back up",
    "failure to cut",
    "failure to cycle",
    "failure to deflate",
    "failure to deliver",
    "failure to deliver energy",
    "failure to deliver shock stimulation",
    "failure to discharge",
    "failure to disconnect",
    "failure to disinfect",
    "failure to eject",
    "failure to fire",
    "failure to fold",
    "failure to form staple",
    "failure to infuse",
    "failure to interrogate",
    "failure to obtain sample",
    "failure to osseointegrate",
    "failure to power up",
    "failure to prime",
    "failure to pump",
    "failure to read input signal",
    "failure to recalibrate",
    "failure to reset",
    "failure to run on battery",
    "failure to seal",
    "failure to select signal",
    "failure to sense",
    "failure to shut off",
    "failure to transmit record",
    "failure to unfold or unwrap",
    "failure to zero",
    "false alarm",
    "false negative result",
    "false positive result",
    "filling problem",
    "filtration problem",
    "fire",
    "firing problem",
    "fitting problem",
    "flaked",
    "flare or flash",
    "fluid blood leak",
    "flushing problem",
    "fogging",
    "fracture",
    "free or unrestricted flow",
    "fumes or vapors",
    "fungus in device environment",
    "gas air leak",
    "gas output problem",
    "gel leak",
    "gradient increase",
    "grounding malfunction",
    "high capture threshold",
    "high impedance",
    "high ph",
    "high readings",
    "high sensing threshold",
    "high test results",
    "illegible information",
    "image display error artifact",
    "image orientation incorrect",
    "impedance problem",
    "implant subsidence",
    "imprecision",
    "improper chemical reaction",
    "improper flow or infusion",
    "improper or incorrect procedure or method",
    "inability to auto fill",
    "inability to irrigate",
    "inaccurate delivery",
    "inaccurate flow rate",
    "inaccurate information",
    "inaccurate synchronization",
    "inadequacy of device shape and or size",
    "inadequate filtration process",
    "inadequate inappropriate treatment or diagnostic exposure",
    "inadequate instructions for healthcare professional",
    "inadequate instructions for non healthcare professional",
    "inadequate lubrication",
    "inadequate or insufficient training",
    "inadequate treatment disease progression",
    "inadequate ultra filtration",
    "inadequate user interface",
    "inappropriate audible prompt feedback",
    "inappropriate inadequate shock stimulation",
    "inappropriate or unexpected reset",
    "inappropriate tactile prompt feedback",
    "inappropriate waveform",
    "inaudible or unclear audible prompt feedback",
    "incomplete coaptation",
    "incomplete or inadequate connection",
    "incomplete or inadequate priming",
    "incomplete or missing packaging",
    "incorrect inadequate or imprecise result or readings",
    "incorrect interpretation of signal",
    "incorrect measurement",
    "increase in pressure",
    "increase in suction",
    "increased pump speed",
    "increased sensitivity",
    "inflation problem",
    "insufficient cooling",
    "insufficient flow or under infusion",
    "insufficient heating",
    "intermittent capture",
    "intermittent communication failure",
    "intermittent continuity",
    "intermittent energy output",
    "intermittent infusion",
    "intermittent loss of power",
    "intermittent program or algorithm execution",
    "intermittent shock stimulation",
    "interrogation problem",
    "intravalvular regurgitation",
    "key or button unresponsive not working",
    "lack of effect",
    "lack of maintenance documentation or guidelines",
    "leak splash",
    "loose or intermittent connection",
    "loosening of implant not related to bone ingrowth",
    "loss of data",
    "loss of or failure to bond",
    "loss of osseointegration",
    "loss of power",
    "loss of threshold",
    "low audible alarm",
    "low impedance",
    "low ph",
    "low readings",
    "low sensing threshold",
    "low test results",
    "malposition of device",
    "material deformation",
    "material discolored",
    "material disintegration",
    "material erosion",
    "material fragmentation",
    "material frayed",
    "material invagination",
    "material opacification",
    "material perforation",
    "material protrusion extrusion",
    "material puncture hole",
    "material rupture",
    "material separation",
    "material split cut or torn",
    "material too rigid or stiff",
    "material too soft flexible",
    "material twisted bent",
    "measurement system incompatibility",
    "mechanical jam",
    "mechanics altered",
    "medical gas supply problem",
    "melted",
    "microbial contamination of device",
    "migration",
    "migration or expulsion of device",
    "misassembled",
    "misassembled during installation",
    "misassembly by users",
    "misassembly during maintenance repair",
    "misconnection",
    "misfire",
    "misfocusing",
    "missed dose",
    "missing information",
    "missing test results",
    "moisture damage",
    "moisture or humidity problem",
    "naturally worn",
    "no audible alarm",
    "no audible prompt feedback",
    "no device output",
    "no display image",
    "no fail safe mechanism",
    "no flow",
    "no pacing",
    "no pressure",
    "no tactile prompts feedback",
    "no visual prompts feedback",
    "noise audible",
    "non reproducible results",
    "nonstandard device",
    "obstruction of flow",
    "off label use",
    "operating system becomes nonfunctional",
    "operating system version or upgrade problem",
    "optical decentration",
    "optical discoloration",
    "optical distortion",
    "optical obstruction",
    "osseointegration problem",
    "output above specifications",
    "output below specifications",
    "over sensing",
    "overcorrection",
    "overdose",
    "overfill",
    "overheating of device",
    "pacemaker found in back up mode",
    "pacing asynchronously",
    "pacing inadequately",
    "pacing intermittently",
    "pacing problem",
    "packaging problem",
    "partial blockage",
    "particulates",
    "patient data problem",
    "patient device incompatibility",
    "patient device interaction problem",
    "peeled delaminated",
    "perivalvular leak",
    "physical resistance sticking",
    "pitted",
    "pocket stimulation",
    "poor quality image",
    "poor visibility",
    "positioning failure",
    "positioning problem",
    "powder leak",
    "power conditioning problem",
    "power problem",
    "precipitate in device or device ingredient",
    "premature activation",
    "premature discharge of battery",
    "premature elective replacement indicator",
    "premature end of life indicator",
    "premature indicator activation",
    "premature separation",
    "pressure problem",
    "priming problem",
    "problem with removal of enzymatic cleaner",
    "problem with software installation",
    "problem with sterilization",
    "product quality problem",
    "program or algorithm execution failure",
    "program or algorithm execution problem",
    "pumping problem",
    "pumping stopped",
    "radiation leak",
    "radiation output failure",
    "radiation output problem",
    "radiation overdose",
    "radiation overexposure",
    "radiation underdose",
    "radiation underexposure",
    "radiofrequency interference rfi",
    "reflux within device",
    "reprogramming of device",
    "reset problem",
    "residue after decontamination",
    "restricted flow rate",
    "retraction problem",
    "scratched material",
    "self activation or keying",
    "sensing intermittently",
    "separation failure",
    "separation problem",
    "sharp edges",
    "shielding failure",
    "shipping damage or problem",
    "short fill",
    "signal artifact noise",
    "smoking",
    "solder joint fracture",
    "sparking",
    "stretched",
    "structural problem",
    "suction failure",
    "suction problem",
    "tactile prompts feedback",
    "tear rip or hole in device packaging",
    "telemetry discrepancy",
    "therapeutic or diagnostic output failure",
    "therapeutic response decreased",
    "therapeutic response increased",
    "therapy delivered to incorrect body area",
    "thermal decomposition of device",
    "thickening of material",
    "tidal volume fluctuations",
    "unable to obtain readings",
    "unauthorized access to computer system",
    "unclear information",
    "under sensing",
    "undercorrection",
    "underdose",
    "unexpected color",
    "unexpected shutdown",
    "unexpected therapeutic effects",
    "unexpected therapeutic results",
    "unexpected unintended radiation output",
    "unintended application program shut down",
    "unintended collision",
    "unintended compatibility",
    "unintended deflation",
    "unintended ejection",
    "unintended electrical shock",
    "unintended movement",
    "unintended power up",
    "unintended system motion",
    "unraveled material",
    "unsealed device packaging",
    "unspecified valve regurgitation",
    "unstable",
    "unstable capture threshold",
    "use of incorrect control treatment settings",
    "ventilation problem in device environment",
    "vibration",
    "visual prompts will not clear",
    "volume accuracy problem",
    "wireless communication problem",
    "wrong label"
  ),
  no_harm = c(
    "misassembled",
    "no clinical signs symptoms or conditions",
    "no health consequences or impact",
    "problem identified before clinical use exposure",
    "problem identified during non clinical procedure",
    "prophylactic removal due to corrective action"
  ),
  other = c(
    "angioedema",
    "anaphylactic shock",
    "anaphylactoid anaphylaxis",
    "aortic valve insufficiency regurgitation",
    "aortic valve stenosis",
    "awareness during anaesthesia",
    "bowel burn",
    "bowel perforation",
    "burn s",
    "burning sensation",
    "cardiac arrest",
    "cardiac enzyme elevation",
    "cardiac septal defect residual shunt",
    "caustic chemical burns",
    "chemical exposure",
    "compartment syndrome",
    "concussion",
    "cryogenic burn",
    "dehydration",
    "diaphoresis",
    "electric shock",
    "erythema",
    "fatigue",
    "foreign body in patient",
    "full thickness third degree burn",
    "hot flashes flushes",
    "heart failure congestive heart failure",
    "hypersensitivity allergic reaction",
    "hyperthermia",
    "hypothermia",
    "intraoperative cardiac valve injury",
    "low cardiac output",
    "mitral perforation",
    "mitral valve insufficiency regurgitation",
    "mitral valve stenosis",
    "myocardial contusion",
    "myocarditis",
    "oversedation",
    "partial thickness second degree burn",
    "procedural complications",
    "radiation burn",
    "rash",
    "reaction to medicinal component of device",
    "recognised device or procedural complication",
    "shock from patient lead s",
    "skin burning sensation",
    "skin discoloration",
    "skin erosion",
    "skin inflammation irritation",
    "superficial first degree burn",
    "transfusion reaction",
    "tricuspid valve insufficiency regurgitation",
    "tricuspid valve stenosis",
    "undesired nerve stimulation",
    "unspecified heart problem",
    "urticaria",
    "valvular insufficiency regurgitation",
    "valvular stenosis",
    "vasodilatation",
    "wheal s"
  )
)

# Any normalized MAUDE term not listed above remains visible here so the
# manual index can be extended over time without losing coverage.
maude_all_terms <-
  dplyr::bind_rows(maude_annex_codes) |>
  dplyr::distinct(annex, imdrf_code, .keep_all = TRUE) |>
  dplyr::transmute(
    term = normalize_maude_terms(term)
  ) |>
  dplyr::distinct(term) |>
  dplyr::pull(term) |>
  sort()

maude_indexed_terms <- sort(unique(unlist(
  maude_complication_index,
  use.names = FALSE
)))

maude_complication_index$not_indexed <- setdiff(
  maude_all_terms,
  maude_indexed_terms
)

stopifnot(
  setequal(
    maude_all_terms,
    unique(unlist(maude_complication_index, use.names = FALSE))
  )
)


# Data saving ----
usethis::use_data(
  complication_definitions,
  maude_complication_index,
  overwrite = TRUE
)
