# Graphical Assessment of Amplitude and Acrophse {{{ ====

#' @title Graphical Assessment of Amplitude and Acrophase
#'
#' @decription This is a ggplot-styled graphical representation of the ellipse region generated by the cosinor analysis. It requires the cosinor model to be fit with the model \code{\link{cosinor}}. It uses the amplitude,
#'
#' @param model This is a `cosinor` model generated by the function in this package. The function expects components generated by the function to be returned.
#' @return ggplot object that has has multiple components


theta_clock <- seq(0, 2*pi, length.out = 24^2)
clock <- cbind(2*amp*cos(theta_clock), 2*amp*sin(theta_clock))

rad <- seq(0, 2*pi-pi/4, by = pi/4)
rad_clock <- cbind(2.2*amp*cos(rad), 2.2*amp*sin(rad))

ggplot() +
	xlim(-2.5 * amp, 2.5*amp) +
	ylim(-2.5 * amp, 2.5*amp) +
	theme_minimal() +
	geom_line(aes(x = gseq, y = bs1), col = "cornflowerblue", size = 1) +
	geom_line(aes(x = gseq, y = bs2), col = "cornflowerblue", size = 1) +
	geom_line(aes(
		x = c(0, gamma),
		y = c(0, beta)
	), lty = 1, size = 1, col = "grey") +
	geom_line(aes(
		x = c(gamma, -2 * amp * sin(phi)),
		y = c(beta, 2 * amp * cos(phi)),
		group = 0
	), size = 1, col = "indianred4", lty = 3) +
	geom_line(aes(x = c(0,0), y = c(-2*amp, 2*amp)), lty = 5) +
	geom_line(aes(y = c(0,0), x = c(-2*amp, 2*amp)), lty = 5) +
	xlab(expression(paste(gamma))) +
	ylab(expression(paste(beta))) +
	geom_path(aes(x = clock[,1], y = clock[,2]), col = "grey") +
	geom_path(aes(x = 1.2*clock[,1], y = 1.2*clock[,2]), col = "grey") +
	annotate(
		geom = "text", x = rad_clock[,1], y = rad_clock[,2],
		label = paste(rad*180/pi, "\u00B0")
	)



# }}}